#!/bin/bash

# This bash script runs the gerby builder on behalf of the crontab

echo "--------------------------------------------------------------"
date
echo "--------------------------------------------------------------"

$HOME/.local/bin/lpilGerbyBuilder $HOME/LpilGerby $HOME/.config/lpil/config.yaml

echo "--------------------------------------------------------------"
date
echo "--------------------------------------------------------------"
